- name: DB configure
  hosts: db
  become: yes
  vars:
    user: root
    password: ExpenseApp@1
    host_name: 52.90.196.118
  tasks:
  - name: install mysql
    #ansible.builtin.dnf:
    dnf:
      name: mysql-server
      state: latest

  - name: start and enable mysql
    #ansible.builtin.service:
    service:
      name: mysqld
      state: started
      enabled: yes

  - name: checking mysql root setup 
    #community.mysql.mysql_info:
    mysql_info:
      login_user: "{{user}}"
      login_password: "{{password}}"
      login_host: "{{host_name}}"
      filter: version
    ignore_error: yes
    register: mysql_connection_output

  - name: Print Output
    debug:
      msg: "LogIn OutPut is: {{mysql_connection_output}} "        